# VERİ BİLİMİ İÇİN PYTHON PROGRAMLAMA
###############################################
# - NumPy
# - Pandas
# - Veri Görselleştirme: Matplotlib & Seaborn
# - %keşifsel Veri Analizi

#NUMPY (Numeric Python)

##Numpy i yüklemek

In [ ]:
import numpy as np

In [ ]:
a=[1,2,3,4]
b=[2,3,4,5]

In [ ]:
a*b

TypeError: ignored

In [ ]:
ab=[]

In [ ]:
for i in range(0,len(a)):
  ab.append(a[i]*b[i])

In [ ]:
ab

[2, 6, 12, 20]

In [ ]:
a=np.array([1,2,3,4])
b=np.array([2,3,4,5])

In [ ]:
a*b

array([ 2,  6, 12, 20])

In [ ]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [ ]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [ ]:
a=np.array([1,2,3],dtype=complex)

In [ ]:
a

array([1.+0.j, 2.+0.j, 3.+0.j])

In [ ]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.random.randint(0,10,size=10)

array([5, 2, 4, 5, 6, 6, 8, 5, 4, 5])

In [ ]:
np.random.normal(10,4,(3,4))  #ilk rakam mean, ikincisi standart sapması, ücüncü ise boyutu

array([[ 4.3888685 , 10.83487313,  4.74872022,  6.64010895],
       [13.01978335, 14.81579244, 12.22266158, 15.36872452],
       [16.00445454,  5.55425414,  6.48009812, 11.32138019]])



*   ndim=boyut sayısı
*   shape=boyut bilgisi
*   size=toplam eleman sayısı
*   dtype=array veri yapısı



In [ ]:
a=np.random.randint(1,10,size=5)

In [ ]:
a

array([4, 9, 9, 8, 5])

In [ ]:
a.ndim

1

In [ ]:
a.shape

(5,)

In [ ]:
a.size

5

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a=np.array([[1,2,3],[4,5,6]])

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a.ndim

2

In [ ]:
a.size

6

In [ ]:
a=np.arange(24)

In [ ]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
a.ndim

1

In [ ]:
b=a.reshape(2,4,3)

In [ ]:
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [ ]:
b.ndim

3

In [ ]:
x=np.ones(5)

In [ ]:
x

array([1., 1., 1., 1., 1.])

In [ ]:
a=np.ones((5),dtype=np.int)

<ipython-input-36-8609f0c1f13d>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a=np.ones(5,dtype=np.int)


In [ ]:
a

array([1, 1, 1, 1, 1])

In [ ]:
x=np.ones([2,2],dtype=int)

In [ ]:
x

array([[1, 1],
       [1, 1]])

In [ ]:
x=np.arange(10,30,5)

In [ ]:
x

array([10, 15, 20, 25])

In [ ]:
np.random.randint(1,10,size=9)

array([9, 2, 3, 5, 7, 7, 1, 5, 6])

In [ ]:
np.random.randint(1,10,size=9).reshape(3,3)

array([[6, 2, 8],
       [4, 1, 5],
       [9, 5, 4]])

In [ ]:
a=np.random.randint(10,size=10)

In [ ]:
a

array([6, 0, 4, 3, 9, 7, 1, 5, 5, 5])

In [ ]:
a[0]

6

In [ ]:
a[0:5]

array([6, 0, 4, 3, 9])

In [ ]:
a[0]=999

In [ ]:
a

array([999,   0,   4,   3,   9,   7,   1,   5,   5,   5])

In [ ]:
m=np.random.randint(10,size=(3,5))

In [ ]:
m

array([[1, 4, 8, 4, 7],
       [3, 8, 2, 3, 6],
       [4, 2, 5, 7, 5]])

In [ ]:
m[0,0]

1

In [ ]:
m[1,2]

2

In [ ]:
m[1,2]=7897897

In [ ]:
m

array([[      1,       4,       8,       4,       7],
       [      3,       8, 7897897,       3,       6],
       [      4,       2,       5,       7,       5]])

In [ ]:
v=np.arange(0,30,3)

In [ ]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [ ]:
v[1]

3

In [ ]:
v[2]

6

In [ ]:
v[3]

9

In [ ]:
catch=[1,2,3]

In [ ]:
v[catch]

array([3, 6, 9])

In [ ]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [ ]:
np.subtract(v,1)

array([-1,  2,  5,  8, 11, 14, 17, 20, 23, 26])

In [ ]:
np.add(v,1)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28])

In [ ]:
np.mean(v)

13.5

In [ ]:
np.sum(v)

135

In [ ]:
np.min(v)

0

In [ ]:
np.max(v)

27

In [ ]:
np.var(v)

74.25